const video = document.getElementById('video')
const hp = document.getElementById('hp')
const many = document.getElementById('$')
const radiation = document.getElementById('radiation')
const audio = document.getElementById('bgMusic5')